name: Install-Export-Deploy

on:
  push:
    branches:
      - master


jobs:
  windows:

    runs-on: windows-2016

    steps:

    - name: Install dependencies
      run: |
        vcpkg install qt5-base:x64-windows qt5-svg:x64-windows qt5-tools:x64-windows zlib:x64-windows
        vcpkg install libqrencode:x64-windows

    - name: Export
      run: |
        vcpkg export --zip qt5-base:x64-windows qt5-svg:x64-windows qt5-tools:x64-windows zlib:x64-windows libqrencode:x64-windows
        move C:\vcpkg\vcpkg-export-*.zip vcpkg-export.zip

    - name: Deploy
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: vcpkg-export.zip
        asset_name: vcpkg-export.zip
        tag: test
        overwrite: true
