name: Install-Export-Deploy

on:
  push:
    branches:
      - master

jobs:
  windows:

    runs-on: windows-2016

    steps:

    - name: Install dependencies
      run: |
        vcpkg install libqrencode:x64-windows
	
    - name: Export
      run: |
        vcpkg export --zip qt5-base qt5-svg qt5-tools zlib libqrencode

#    - name: Deploy
#      uses: svenstaro/upload-release-action@v1-release
#      with:
#        repo_token: ${{ secrets.GITHUB_TOKEN }}
#        file: ${{ format('build/glabels-{0}-x86_64.AppImage', steps.cmake_configure.outputs.version) }}
#        asset_name: ${{ format('build/glabels-{0}-x86_64.AppImage', steps.cmake_configure.outputs.version) }}
#        tag: ${{ steps.cmake_configure.outputs.version }}
#        overwrite: true
